/'
Задание:
В библиотеке хранятся книги (издания). Каждая книга (издание) имеет уникальный идентификатор, название, автора, год
издания и количество страниц. Книги издаются издательствами, у которых есть название и адрес. В библиотеке есть
экземпляры книг (физические/электронные копии издания). Каждый экземпляр имеет уникальный идентификатор и положение на
полке. Экземпляр книги связан с конкретной книгой. Книги могут принадлежать одной или нескольким категориям. Категории
могут быть вложенными (одна категория может быть подкатегорией другой). У каждой категории есть название. В библиотеке
есть читатели. Каждый читатель имеет уникальный идентификатор, имя, фамилию, адрес и дату рождения. Читатель может брать
книги на определенный срок. Для каждой выдачи книги записывается дата, когда книга была взята, планируемая дата возврата
и фактическая дата возврата (если книга уже возвращена).
'/
@startuml ERD_Example

!function $pk($a)
!return "<color:RoyalBlue>" + $a + " <<PK>></color>"
!endfunction

!function $unique($a)
!return "<color:Crimson>" + $a + " <<unique>></color>"
!endfunction

!function $setBold($a)
!return "<b>" + $a + " </b>"
!endfunction

skinparam BackgroundColor SeaShell
skinparam LegendBackgroundColor MistyRose
skinparam LegendBorderColor PaleVioletRed
skinparam LegendFontColor PaleVioletRed

skinparam Class {
    HeaderBackgroundColor PaleGreen
}
skinparam TitleFontColor Sienna

Title ER‑диаграмма "Библиотечная система"

entity "$setBold("Книга")" as Book {
    * $pk("Идентификатор")
    * Название
    * Автор
    * Год_издания
    * Количество_страниц
}

entity "$setBold("Издательство")" as Publisher {
    * $pk("Идентификатор")
    * Название
    * Адрес
}

entity "$setBold("Экземпляр")" as Copy {
    * $pk("Идентификатор")
    * Положение_на_полке
    Тип (физический/электронный)
}

entity "$setBold("Категория")" as Category {
    * $pk("Идентификатор")
    * Название
}

entity "$setBold("Читатель")" as Reader {
    * $pk("Идентификатор")
    * Имя
    * Фамилия
    * Адрес
    * Дата_рождения
}
entity "$setBold("Выдача")" as Loan {
    * $pk("Идентификатор")
    * Дата_выдачи
    * Планируемая_дата_возврата
    * Фактическая_дата_возврата
}

' Издательство публикует книгу (один ко многим)
Publisher ||--o{ Book : "издаёт"

' У книги есть экземпляры (один ко многим)
Book ||--o{ Copy : "имеет_экземпляры"

' Книга может принадлежать нескольким категориям (один ко многим)
Book ||--o{ Category : "принадлежит_категориям"

' Категории могут быть вложенными (рекурсивная связь)
Category }o--o{ Category : "подкатегория_для"

' Читатель берет книги (выдача) (один ко многим)
Reader ||--o{ Loan : "берёт_книги"

' Экземпляр связон с выдачей (один ко многим)
Copy ||--o{ Loan : "выдан_в"

@enduml