Table station {
  stat_nr int [pk]
  name string
}

Table room {
  stat_nr int [ref: > station.stat_nr]
  room_nr int
  beds int

  Indexes {
    (stat_nr, room_nr) [pk]
  }
}

Table station_personnel {
  pers_nr int [pk]
  name string
  stat_nr int [not null, ref: > station.stat_nr]
}

Table doctor {
  pers_nr int [pk, ref: > station_personnel.pers_nr]
  area string
  rank string
}

Table caregiver {
  pers_nr int [pk, ref: > station_personnel.pers_nr]
  qualification string
}

Table patient {
  patient_nr int [pk]
  name string
  disease string
}

Table admission {
  patient_nr int [pk, ref: > patient.patient_nr]
  stat_nr int [not null, ref: > room.stat_nr]
  room_nr int [not null, ref: > room.room_nr]
  from_date date
  to_date date
}

Table treats {
  doctor_nr int [ref: > doctor.pers_nr]
  patient_nr int [ref: > patient.patient_nr]

  Indexes {
    (doctor_nr, patient_nr) [pk]
  }
}
