Table reader {
  reader_number int [pk]
  firs_name string
  last_name string
  birthday datetime
  address string
}

Table publisher {
  name string [pk]
  address string
}

Table category {
  category_name string [pk]
  parent_category string [ref: > category.category_name]
}

Table book {
  ISBN string [pk]
  title string
  author string
  year int
  number_of_pages int
  publisher_name string [ref: > publisher.name]
}

Table copy {
  ISBN string [pk, ref: > book.ISBN]
  copy_number int [pk]
  position string
}

Table borrows {
  reader_number int [ref: > reader.reader_number]
  ISBN string
  copy_number int
  return_date date

  Indexes {
    (reader_number, ISBN, copy_number) [pk]
  }
}

Table book_category {
  ISBN string [ref: > book.ISBN]
  category_name string [ref: > category.category_name]

  Indexes {
    (ISBN, category_name) [pk]
  }
}
