Table city {
  name string
  region string
  Indexes {
    (name, region) [pk]
  }
}

Table station {
  name string [pk]
  tracks int
  city_name string [not null, ref: > city.name]
}

Table train {
  train_nr int [pk]
  length int
  start_station string [not null, ref: > station.name]
  end_station string [not null, ref: >  station.name]
}

Table connected {
  train_nr int [ref: >  train.train_nr]
  station_name string [ref: >  station.name]
  arrival_time time
  departure_time time

  Indexes {
    (train_nr, station_name) [pk]
  }
}
